#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Term-UI
Version  : 0.46
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Term-UI-0.46.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Term-UI-0.46.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libterm-ui-perl/libterm-ui-perl_0.46-1.debian.tar.xz
Summary  : 'User interfaces via Term::ReadLine made easy'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Term-UI-license
Requires: perl-Term-UI-man
Requires: perl(Log::Message::Simple)
BuildRequires : perl(Log::Message::Simple)

%description
Please refer to 'perldoc Term::UI' after installation for details.
#####################################################################

%package license
Summary: license components for the perl-Term-UI package.
Group: Default

%description license
license components for the perl-Term-UI package.


%package man
Summary: man components for the perl-Term-UI package.
Group: Default

%description man
man components for the perl-Term-UI package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Term-UI-0.46
mkdir -p %{_topdir}/BUILD/Term-UI-0.46/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Term-UI-0.46/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Term-UI
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Term-UI/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Term/UI.pm
/usr/lib/perl5/site_perl/5.26.1/Term/UI/History.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Term-UI/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Term::UI.3
/usr/share/man/man3/Term::UI::History.3
